### ISSUE TITLE
Server cannot be reached

### ISSUE THREAD

**Issue by zeelmavani** [stefanjudis/contentful-graphql-playground-app#3]
When I opened the playground from the content sidebar, facing issues with the server cannot be reached.

Error is: 
```
{
  "error": "Union type PageContent can only include type PageLanding once."
}
```

Please help ASAP

**Comment by stefanjudis** [comment]
Can you check if the API key you defined for the app, has access to the environment you try to query?

![image](https://user-images.githubusercontent.com/962099/124117685-b56ddb00-da70-11eb-9003-79b9b85b7342.png)

![image](https://user-images.githubusercontent.com/962099/124117708-bc94e900-da70-11eb-984f-505b361f396c.png)

**Comment by zeelmavani** [comment]
Yes. I checked. Please find attached a screenshot.

**Comment by stefanjudis** [comment]
There's no screenshot though. :)

**Comment by zeelmavani** [comment]
![Screenshot 2021-07-01 at 5 16 31 PM](https://user-images.githubusercontent.com/17518837/124120541-82880f00-da91-11eb-8e2e-4f296500da8c.png)

**Comment by stefanjudis** [comment]
Alright, please provide more information, then. It's hard to help without context. :) 

Useful information: the query, the selected environment, and the potential alias.

In the meantime: [you can always use Contentful's default GraphiQL interface](https://www.contentful.com/developers/docs/references/graphql/#/reference/exploring-the-schema-with-graphiql) to write your GraphQL queries.

**Comment by zeelmavani** [comment]
> Alright, please provide more information, then. It's hard to help without context. :)
> 
> Useful information: the query, the selected environment, and the potential alias.
> 
> In the meantime: [you can always use Contentful's default GraphiQL interface](https://www.contentful.com/developers/docs/references/graphql/#/reference/exploring-the-schema-with-graphiql) to write your GraphQL queries and not be blocked. :)

**Comment by stefanjudis** [comment]
I'm confused. Does it work now?

**Comment by zeelmavani** [comment]
> I'm confused. Does it work now?

Nop... Just trying to add a screenshot which shows query and environment details
![Screenshot 2021-07-01 at 5 33 20 PM](https://user-images.githubusercontent.com/17518837/124121651-c7f90c00-da92-11eb-89ce-a3ad78cb866f.png)

**Comment by stefanjudis** [comment]
Okay, then let's not close the issue. :) 

I'll have a look at it when I have a moment. In the meantime, can you try changing the URL in the playground from `.../environments/develop` (that's the environment) to `.../environments/master` and see if that resolves it?

**Comment by zeelmavani** [comment]
> Okay, then let's not close the issue. :)
> 
> I'll have a look at it when I have a moment. In the meantime, can you try changing the URL in the playground from `.../environments/develop` (that's the environment) to `.../environments/master` and see if that resolves it?

Already tried that but no luck.... :(

**Comment by stefanjudis** [comment]
Are you 100% sure you have the correct API key stored in the Playground config?

Can you use [the default GraphiQL](https://www.contentful.com/developers/docs/references/graphql/#/reference/single-resource-fields) and see if you can replicate the issue?

**Comment by zeelmavani** [comment]
If the API key was wrong then it throws an error like 401 right?

**Comment by stefanjudis** [comment]
I've also seen `400` for incorrect API keys. 

> Can you use the default GraphiQL and see if you can replicate the issue?

[Can you please use the default tooling](https://www.contentful.com/developers/docs/references/graphql/#/reference/exploring-the-schema-with-graphiql). And then compare what the playground app does differently. 

And report all information in a single comment so that I can investigate? :)

**Comment by zeelmavani** [comment]
Yes, in short, it returns 4XX if the key is invalid, not 5XX.
I already tried it using Postman and got the exact same response, I will install graphiql and share the complete issue in one comment

**Comment by stefanjudis** [comment]
Thank you. :) Let's figure that one out. 💪

**Comment by zeelmavani** [comment]
**Issue explanation:**

I have two environments - develop and master and a content model with few basic fields and one reference field. The required API access token has been generated with the permission of CDA and CPA APIs, and both the env.

GraphQL API throws an 500 ('internal server error') while trying with the following query (the same can be found in the attached screenshot)
`query gtiStoreEntryQuery {
  gtiStore(id: "<id>") {
    items{
            name
    }
  }
}
`
Error:  Server cannot be reached
`{
    "errors": [
        {
            "message": "Union type PageContent can only include type PageLanding once."
        }
    ]
}`
![Screenshot 2021-07-01 at 8 07 28 PM](https://user-images.githubusercontent.com/17518837/124142700-1369e500-daa8-11eb-8418-efce62bd68d4.png)

**What I have tried so far:** 

1. reEnabled the API key to have access to all environments, In fact, I have two environments only.
2. Tried API for both the environments
3. Tried API in different tools like Contentful's integrated graphql playground, Postman, graphiql and cURL

**Comment by stefanjudis** [comment]
@zeelmavani Thanks for the detailed explanation. 

I think this is now a different problem, and not a problem with the Contentful GraphQL Playground app. The app makes the request accordingly and shows the correct API response. 

It's then rather a problem with the GraphQL API and/or the content you want to access.

Depending on your pricing plan, please reach out to support (contentful.com/support) and/or maybe join the community slack (contentful.com/slack) to seek help from the community.
